# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

parameters:
- name: BUILD
  type: boolean
  default: true
- name: DEPLOY
  type: boolean
  default: false
- name: serviceConnection
  default: 'xxx' 
- name: nameSpace
  default: 'yyy' 
- name: commands
  default: 'zzz' 
- name: arguments
  default: 'xxx' 


resources:
- repo: self

variables:
- template: values.yml

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - ${{ if eq(parameters.BUILD, true) }}:
    - job: Build
      displayName: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker'
          repository: 'bala2805/k8s_project'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            ${{ variables.tag }}
   
  - ${{ if eq(parameters.DEPLOY, true) }}:          
    - job: DEPLOY
      displayName: DEPLOY
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - bash: |
          export WEBREPLICA: ${{variables.WEBREPLICA}}
          export WEB_SERVICEPORT: ${{variables.WEB_SERVICEPORT}}
          export WEBCONTAINER_PORT: ${{variables.WEBCONTAINER_PORT}}
          export IMAGE: ${{variables.IMAGE}}
          export WEB_SERVICE_TYPE: ${{variables.WEB_SERVICE_TYPE}}
          export SQL_CONTAINER_PORT: ${{variables.SQL_CONTAINER_PORT}}
          export SQL_SERVICE_PORT: ${{variables.SQL_SERVICE_PORT}}
          export VOLUME_SQL_NAME: ${{variables.VOLUME_SQL_NAME}}
          export SQL_SERVICE_TYPE: ${{variables.SQL_SERVICE_TYPE}}
          export ACCESSModes: ${{variables.ACCESSModes}}
          export STORAGE_MOUNT: ${{variables.STORAGE_MOUNT}}
          export PVC_NAME:${{variables.PVC_NAME}}
          cat ${{ parameters.arguments }} | envsubst > deployment.yml
      
        displayName: ENV Substitution
      
      - task: Kubernetes@1
        displayName: kubectl apply using arguments
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: ${{ parameters.serviceConnection }}
          namespace: ${{ parameters.nameSpace }}
          command: ${{ parameters.commands }}
          arguments: -f  deployment.yml
