---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
 replicas: ${WEBREPLICA}
 selector:
   matchLabels:
    app: apache
 template:
   metadata:
    labels:
     app: apache
   spec:
    containers:
      - name: apache
        image: ${IMAGE}
        ports:
        - containerPort: ${WEBCONTAINER_PORT}
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
    volumes:
      - name: hostvol
        hostPath:
          path: ./src/
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: ${WEB_SERVICE_TYPE}
  ports:
  - port: ${WEB_SERVICEPORT}
    protocol: TCP
  selector:
    app: apache
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: ${IMAGE}
        name: mysql
        ports:
        - containerPort: ${SQL_CONTAINER_PORT}
          name: mysql8
        volumeMounts:
          - name: ${VOLUME_SQL_NAME}
            mountPath: /var/lib/mysql
      volumes:
      - name: ${VOLUME_SQL_NAME}
        persistentVolumeClaim:
          claimName: ${PVC_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql8-service
  labels:
    app: mysql8
spec:
  type: ${SQL_SERVICE_TYPE}
  ports:
  - port: ${SQL_SERVICE_PORT}
    protocol: TCP
  selector:
    app: mysql8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  labels:
    app: mysql8
spec:
  accessModes:
    - ${ACCESSModes}
  resources:
    requests:
      storage: ${STORAGE_MOUNT}
