---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
 replicas: ${WEBREPLICA}
 selector:
   matchLabels:
    app: apache
 template:
   metadata:
    labels:
     app: apache
   spec:
    containers:
      - name: apache
        image: ${IMAGE}
        ports:
        - containerPort: ${WEBCONTAINER_PORT}
        volumeMounts:
        - name: hostvol
          mountPath: /var/www/html/
      - name: mysql
	    image: ${IMAGE}
        ports:
        - containerPort: ${SQL_CONTAINER_PORT}
          name: mysql8
        volumeMounts:
          - name: ${VOLUME_SQL_NAME}
            mountPath: /var/lib/mysql
      volumes:
      - name: ${VOLUME_SQL_NAME}
        persistentVolumeClaim:
          claimName: ${PVC_NAME}
      - name: hostvol
        hostPath:
          path: ./tmp
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: ${WEB_SERVICE_TYPE}
  ports:
  - port: ${WEB_SERVICEPORT}
    protocol: TCP
  - port: ${SQL_SERVICE_PORT}
    protocol: TCP
  selector:
    app: apache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  labels:
    app: apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${STORAGE_MOUNT}
