---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
 replicas: ${WEBREPLICA}
 selector:
   matchLabels:
    app: apache
 template:
   metadata:
    labels:
     app: apache
   spec:
    containers:
      - name: apache
        image: ${IMAGE}
        ports:
        - name: apache
          containerPort: ${WEBCONTAINER_PORT}
        - name: mysql
          containerPort: ${SQL_CONTAINER_PORT}
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: ${WEB_SERVICE_TYPE}
  ports:
  - name: apache
    port: ${WEB_SERVICEPORT}
    protocol: ${WEB_PROTOCOL}
  - name: sql
    port: ${SQL_SERVICE_PORT}
    protocol: ${SQL_PROTOCOL}
  selector:
    app: apache        
